language: python

addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.32.4_Linux-64bit.deb
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: www.dantswain.com
  target_branch: master
  repo: dantswain/dantswain.github.io
  verbose: true
  on:
    branch: master
