baseURL = "https://dantswain.github.io/"
languageCode = "en-us"
title = "Dan's Blog"

pygmentsCodeFences = true

GoogleAnalytics = "UA-30160681-1"

disqusshortname = "dantswainblog"

disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Dan Swain"

[params]
blogHeader = "<span style=\"font-size: 36px; \">Dan's Blog</span>"
tagline = "something witty"
headerimg = "flockBack.png"

noburger = true

author = "Dan Swain"
authorlocation = "Rochester, NY"
authorwebsite = "https://dantswain.com"

authorbio = "Fellow at simpli.fi. Robotics Ph.D. I like building things. "

cover = "images/flockBack.png"

githubName = "dantswain"
twitterName = "dantswain"

googleAnalyticsUserID = "UA-30160681-1"

[permalinks]
post = "/:year/:month/:day/:title/"


[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
